# Spectre configuration file
# This file is used to configure the plugin's settings.


# Messages
messages:
  # Prefix for all messages sent by Spectre
  prefix: "&6[&eSpectre&6]&7 "
  # Message sent when a player does not have permission to use a command
  no_permission: "You do not have permission to use this command." 
   # Message sent when a command can only be used by players
  player_only: "This command can only be used by players."
  # Message sent when Spectre is enabled
  enabled: "Spectre has been enabled. Use /spectre mode <mode> to change visibility." 
  # Message sent when Spectre is disabled
  disabled: "Spectre has been disabled. You will now see all players." 
  # Message sent when a player changes their visibility mode
  modes: 
    vanish: "Spectre mode set to vanish. Players will disappear completely." 
    ghost: "Spectre mode set to ghost. Players will appear as transparent ghosts." #
    invisible: "Spectre mode set to invisible. Players will be invisible, but their armor may still be visible."
  # Message sent when a player toggles armor visibility
  armor: "Armor visibility has been set to %s."