#####################################################################
#                   Spectre configuration file                      #
#        This file is used to configure the plugin's settings.      #
#####################################################################

# Messages
messages:
  # Prefix for all messages sent by Spectre, set to "" to disable
  prefix: "&6[&eSpectre&6]&7 "
  # Message sent when a player does not have permission to use a command
  no_permission: "You do not have permission to use this command." 
   # Message sent when a command can only be used by players
  player_only: "This command can only be used by players."
  # Message sent when Spectre is enabled
  enabled: "Spectre has been enabled. Use /spectre mode <mode> to change visibility." 
  # Message sent when Spectre is disabled
  disabled: "Spectre has been disabled. You will now see all players." 
  # Message sent when a player changes their visibility mode
  modes: 
    vanish: "Spectre mode set to vanish. Players will disappear completely." 
    ghost: "Spectre mode set to ghost. Players will appear as transparent ghosts." #
    invisible: "Spectre mode set to invisible. Players will be invisible, but their armor may still be visible."
  # Message sent when a player toggles armor visibility. The %s will be replaced with the new visibility setting
  armor: "Armor visibility has been set to %s."
  usage: "Usage: %s"
  reload: "Configuration file reloaded."
  version-check:
    # Message sent when the plugin is up to date
    up-to-date: "Spectre is up to date. Current version: %s."
    # Message sent when the plugin is outdated
    outdated: "Spectre is outdated. The latest version is %s."
    # Message sent when an error occurs while checking for updates
    error: "An error occurred while checking for updates. Please try again later."
  help:
    - "&6Spectre Commands:"
    - "&e/spectre &7- Main command for the Spectre plugin."
    - "&e/spectre help &7- Display this help message."
    - "&e/spectre mode <mode> &7- Change visibility mode (vanish, ghost, invisible)."
    - "&e/spectre armor <visible|hidden> &7- Change armor visibility."
    - "&e/spectre version &7- Display the plugin version."
  help-admin:
    - "&e/spectre check-updates &7- Check for updates."


# Settings

# Whether or not to enable bStats metrics
## What is bStats? https://bstats.org/
enable-bStats: true

# Whether or not to check for updates on startup
check-for-updates: true

defaults:
  # Default visibility mode for players who join the server
  mode: ghost
  # Default armor visibility setting for players who join the server
  armor: boots
  # Radius in blocks for players to be visible in vanish mode
  vanish-radius: 5
  # Default boots type for players who are not wearing any armor
  boots-material: GOLDEN_BOOTS