name: Spectre
main: com.github.dsadriel.spectre.Spectre
version: ${project.version}
api-version: 1.20
description: Spectre is a Minecraft plugin that allows the player to control the visibility of nearby players.
website: https://github.com/dsadriel/spectre
author: dsadriel
depend: [packetevents]


commands:
  spectre:
    description: Main command for the Spectre plugin.
    usage: /spectre
    permission: spectre.use
    aliases: [sp, spec]

permissions:
  spectre.toggle:
    description: Allows the player to toggle the visibility of nearby players
  spectre.mode:
    description: Allows the player to change the visibility mode
  spectre.armor:
    description: Allows the player to change the visibility of armor
  spectre.radius:
    description: Allows the player to set the radius for players to be hidden
  spectre.bypass:
    description: Allows the player to bypass the visibility restrictions
  spectre.admin:
    description: Allows the player to use admin commands