name: Spectre
main: com.github.dsadriel.spectre.Spectre
version: ${project.version}
api-version: 1.20
description: Spectre is a Minecraft plugin that allows the player to control the visibility of nearby players.
website: https://github.com/dsadriel/spectre
author: dsadriel
depend: [packetevents]


commands:
  spectre:
    description: Main command for the Spectre plugin.
    usage: /spectre
    permission: spectre.use
    aliases: [sp, spec]

permissions:
  spectre.toggle:
    description: Allows the player to toggle the visibility of nearby players
  spectre.mode.vanish:
    description: Allows the player to change the visibility mode to vanish
  spectre.mode.ghost:
    description: Allows the player to change the visibility mode to ghost
  spectre.mode.invisible:
    description: Allows the player to change the visibility mode to invisible
  spectre.armor.visible:
    description: Allows the player to change the visibility of armor to visible
  spectre.armor.hidden:
    description: Allows the player to change the visibility of armor to hidden
  spectre.armor.boots:
    description: Allows the player to change the visibility of boots
  spectre.set-radius:
    description: Allows the player to set the radius for players to be hidden
  spectre.bypass:
    description: Allows the player to bypass the visibility restrictions
  spectre.admin:
    description: Allows the player to use admin commands